name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.app
  
jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
